version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ./src:/usr/src:cache
      - node_modules:/usr/src/node_modules
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
