version: '3'

tasks:
  build:
    cmd: docker compose build
  build.no-cache:
    cmd: docker compose build --no-cache
  up:
    cmd: docker compose up -d
  up.build:
    cmd: docker compose up -d --build
  bash:
    cmd: docker compose exec web bash
  lint.write:
    cmd: docker compose exec web npm run lint:write
  lint.check:
    cmd: docker compose exec web npm run lint:check
  down:
    cmd: docker compose down
